version: 2
updates:
  - package-ecosystem: docker
    commit-message:
      prefix: chore(dockerfile)
    directory: /
    open-pull-requests-limit: 1000
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    commit-message:
      prefix: ci(Github Actions)
    directory: /
    open-pull-requests-limit: 1000
    schedule:
      interval: daily
